from __future__ import annotations

ABI_NAME = "opc-export"
ABI_VERSION = "1.0.0"
DEFAULT_EXPORTER_VERSION = "chronohorn-export-0.1"
DEFAULT_LEARNED_STATE_FORMAT = "npy"
DEFAULT_CHECKSUM_ALGORITHM = "blake2b"
__all__ = [
    "ABI_NAME",
    "ABI_VERSION",
    "DEFAULT_EXPORTER_VERSION",
    "DEFAULT_LEARNED_STATE_FORMAT",
    "DEFAULT_CHECKSUM_ALGORITHM",
]
